# Generated by Django 3.1.12 on 2024-08-03 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(blank=True, max_length=100, null=True)),
                ('Creationdate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactusinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=250, null=True)),
                ('EmailId', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNo', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactusquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=250, null=True)),
                ('EmailId', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNo', models.CharField(blank=True, max_length=12, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('PostingDate', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehiclesTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('VehiclesOverview', models.CharField(blank=True, max_length=350, null=True)),
                ('PricePerDay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('FuelType', models.CharField(blank=True, max_length=150, null=True)),
                ('ModelYear', models.CharField(blank=True, max_length=150, null=True)),
                ('SeatingCapacity', models.CharField(blank=True, max_length=150, null=True)),
                ('Vimage1', models.FileField(blank=True, null=True, upload_to='')),
                ('Vimage2', models.FileField(blank=True, null=True, upload_to='')),
                ('Vimage3', models.FileField(blank=True, null=True, upload_to='')),
                ('Vimage4', models.FileField(blank=True, null=True, upload_to='')),
                ('Vimage5', models.FileField(blank=True, null=True, upload_to='')),
                ('AirConditioner', models.CharField(blank=True, max_length=50, null=True)),
                ('PowerDoorLocks', models.CharField(blank=True, max_length=50, null=True)),
                ('AntiLockBrakingSystem', models.CharField(blank=True, max_length=50, null=True)),
                ('BrakeAssist', models.CharField(blank=True, max_length=50, null=True)),
                ('PowerSteering', models.CharField(blank=True, max_length=50, null=True)),
                ('DriverAirbag', models.CharField(blank=True, max_length=50, null=True)),
                ('PassengerAirbag', models.CharField(blank=True, max_length=50, null=True)),
                ('PowerWindows', models.CharField(blank=True, max_length=50, null=True)),
                ('CDPlayer', models.CharField(blank=True, max_length=50, null=True)),
                ('CentralLocking', models.CharField(blank=True, max_length=50, null=True)),
                ('CrashSensor', models.CharField(blank=True, max_length=50, null=True)),
                ('LeatherSeats', models.CharField(blank=True, max_length=50, null=True)),
                ('RegDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateField(blank=True, null=True)),
                ('VehiclesBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.brands')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactNo', models.CharField(blank=True, max_length=12, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=250, null=True)),
                ('City', models.CharField(blank=True, max_length=150, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('RegDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingNumber', models.CharField(blank=True, max_length=150, null=True)),
                ('FromDate', models.DateField(blank=True, null=True)),
                ('ToDate', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=150, null=True)),
                ('PostingDate', models.DateTimeField(auto_now_add=True)),
                ('LastUpdationDate', models.DateField(blank=True, null=True)),
                ('VehicleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.vehicles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.userdetails')),
            ],
        ),
    ]
