# Generated by Django 3.1.12 on 2024-09-19 16:12

from django.db import migrations, models


def set_default_address(apps, schema_editor):
    UserDetails = apps.get_model('carRental', 'UserDetails')
    # Set a default value for Address for existing records
    UserDetails.objects.filter(Address__isnull=True).update(Address='Default Address')


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0003_alter_booking_id_alter_brands_id_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_address),  # Add this line
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactusquery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Address',
            field=models.CharField(max_length=250),  # Change this line to make Address non-nullable
        ),
    ]
