# Generated by Django 5.1.2 on 2024-10-18 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0005_booking_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='AntiLockBrakingSystem',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='BrakeAssist',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='CDPlayer',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='CentralLocking',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='CrashSensor',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='DriverAirbag',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='LeatherSeats',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='PassengerAirbag',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='PowerDoorLocks',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='PowerSteering',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='PowerWindows',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='ContactNo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='EmailId',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactusquery',
            name='ContactNo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactusquery',
            name='EmailId',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactusquery',
            name='Message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactusquery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='City',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ContactNo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='UpdationDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='AirConditioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='ModelYear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='PricePerDay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='SeatingCapacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='VehiclesOverview',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
