# Generated by Django 5.1.2 on 2024-10-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0006_remove_vehicles_antilockbrakingsystem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('ContactNo', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=250)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
