# Generated by Django 5.1.2 on 2024-10-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0007_tempuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='Address',
            field=models.TextField(max_length=250),
        ),
    ]
