# Generated by Django 5.1.2 on 2024-10-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0008_alter_tempuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='LastUpdationDate',
            field=models.DateField(auto_now=True),
        ),
    ]
