# Generated by Django 5.1.2 on 2024-10-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0009_alter_booking_lastupdationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='invoice',
        ),
        migrations.AddField(
            model_name='booking',
            name='PaymentStatus',
            field=models.CharField(default='Pending', max_length=150, null=True),
        ),
    ]
