# Generated by Django 5.1.2 on 2024-10-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0010_remove_booking_invoice_booking_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
