# Generated by Django 5.1.2 on 2024-10-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0011_booking_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='QR/'),
        ),
    ]
