# Generated by Django 5.1.2 on 2024-10-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0012_booking_qr_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_image_url',
        ),
    ]
