# Generated by Django 4.2.19 on 2025-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0013_remove_booking_qr_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='license_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='state',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
