# Generated by Django 4.2.19 on 2025-04-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0014_userdetails_license_no_userdetails_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
