# Generated by Django 4.2.19 on 2025-04-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0015_userdetails_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='AntiLockBrakingSystem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='BrakeAssist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='CDPlayer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='CentralLocking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='CrashSensor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='DriverAirbag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='LeatherSeats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='PassengerAirbag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='PowerDoorLocks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='PowerSteering',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='PowerWindows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='AirConditioner',
            field=models.BooleanField(default=True),
        ),
    ]
