# Generated by Django 4.2.19 on 2025-04-20 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carRental', '0016_userdetails_is_owner_vehicles_antilockbrakingsystem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
